#!/usr/bin/env python3
import time, requests, json

get_url ='https://iot.lisha.ufsc.br/api/get.php'

epoch = int(time.time() * 1000000)
query = {
        'series' : {
            'version' : '1.1',
            'unit'    : 2224179500, # 2224441636 = TSTP::Unit::Length; 2224179500 = Amount_of_Substance
            'x'       : 37335860, # 37331860 e 37335860
            'y'       : -42829040,
            'z'       : -28887290,
            'r'       : 10*100,
            't0'      : 0,
            't1'      : epoch,
            'dev'     : 1, # + 2047 = water level
        },
        'credentials' : {
        	'domain'   : 'tutorial',
            'username' : 'tutorial',
            'password' : 'tuto20182'
        }
    }
session = requests.Session()
session.headers = {'Content-type' : 'application/json'}
response = session.post(get_url, json.dumps(query))

# print("Get [", str(response.status_code), "] (", len(query), ") ", query, sep='')
if response.status_code == 200:
	print("200:", json.dumps(response.json(), indent=4, sort_keys=False))
elif response.status_code == 400:
    print("400: bad formatting")
elif response.status_code == 204:
    print("204: series successfully created")
else:
    print("Error ", response.status_code, sep = '')
